name: CI-DEPLOY-K8S

on:
  push:
    branches:
      - feature/TASK-1609-k8s-9

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: pytest Module_15/deploy_k8s/tests/ -v
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Verify minikube is running
        run: minikube status
        
      - name: Set K8s Context
        run: kubectl config use-context minikube
      
      - name: Verify cluster connection
        run: kubectl cluster-info
      
      - name: Deploy to Kubernetes
        run: kubectl apply -f Module_15/action/fastapi-deployment.yml
      
      - name: Verify deployment
        run: kubectl rollout status deployment/fastapi-book-service
